### PR TITLE
Allow transparent background

### PR DESCRIPTION
**Pull request by antonmosich**
While all other colors should be possible with the current version, it's not possible to have a transparent background on the wallpaper. This PR implements the possibility to set backgroundColor to "transparent".

### CODE REVIEW

**Comment by lunik1** [comment]
If being able to set the alpha is useful, it might be preferable to be able to set it for any element and at any level. What is your use case for this?

**Comment by antonmosich** [comment]
I'm placing the nix-wallpaper on top of another wallpaper for the final wallpaper, so I (currently) only need transparent background, but I could (and will) try to come up with a solution. The best way I could think of would be to be able to set transparency via optional extra 2 digits in the hex code, so #rrggbbaa. Do you agree?

**Comment by lunik1** [comment]
Yes, I think that would be ideal. Old six-digit hex codes should still work, though.

**Comment by antonmosich** [comment]
This is what I came up with. I'll rebase before merging, so please don't merge yet. The flake.lock update was needed in order for `lib.fromHexString` to be available. This might cause breakage for users which override nix-wallpapers nixpkgs to a version older than 3 months (as of now).

**Comment by lunik1** [comment]
Thanks! I'll try to review this week.

**Comment by lunik1** [comment]
Looks good, could you update the README too?

**Comment by antonmosich** [comment]
Great, I will try to update the README tomorrow or the day after.

**Comment by lunik1** [comment]
Were you ready to merge this?

**Comment by antonmosich** [comment]
Yes! Thanks for asking.

**Pull request merged**
